Repository airsonic/airsonic, pull requests merged in 2019-10, with the labels that each got.

#1244 Make the logout icon/image cliquable
  airsonic-main/src/main/webapp/WEB-INF/jsp/top.jsp
Labels: usability

#1264 Expunge search index
  airsonic-main/src/main/java/org/airsonic/player/controller/MusicFolderSettingsController.java
  airsonic-main/src/main/java/org/airsonic/player/dao/AlbumDao.java
  airsonic-main/src/main/java/org/airsonic/player/dao/ArtistDao.java
  airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
  airsonic-main/src/main/java/org/airsonic/player/service/search/DocumentFactory.java
  airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java
  airsonic-main/src/test/java/org/airsonic/player/service/search/IndexManagerTestCase.java
Labels: backend, enhancement, performance, search, usability

#1241 Handle nulls when processing cover art better
  airsonic-main/src/main/java/org/airsonic/player/controller/CoverArtController.java
Labels: code quality

#1232 Media file scan will now heed configured music/video file types
  airsonic-main/src/main/java/org/airsonic/player/ajax/CoverArtService.java
  airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
Labels: backend, feature request, performance, usability

#607 Option to disable timestamps during scan
  airsonic-main/src/main/java/org/airsonic/player/dao/AlbumDao.java
  airsonic-main/src/main/java/org/airsonic/player/dao/ArtistDao.java
  airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
  airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
  airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
Labels: enhancement

#1250 Remove radeox
  airsonic-main/pom.xml
  airsonic-main/src/main/java/org/airsonic/player/taglib/WikiTag.java
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_bg.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ca.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_cs.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_da.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_de.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_el.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en_GB.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_es.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_et.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_fi.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_fr.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_is.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_it.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ja_JP.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ko.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_mk.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_nl.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_nn.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_no.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pl.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt_BR.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt_PT.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ru.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_sl.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_sv.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_uk.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_zh_CN.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_zh_TW.properties
  airsonic-main/src/main/webapp/WEB-INF/jsp/albumMain.jsp
  airsonic-main/src/main/webapp/WEB-INF/jsp/artistMain.jsp
  airsonic-main/src/main/webapp/WEB-INF/jsp/generalSettings.jsp
  airsonic-main/src/main/webapp/WEB-INF/jsp/home.jsp
  airsonic-main/src/main/webapp/WEB-INF/jsp/login.jsp
Labels: breaking change, code quality, dependencies

#1050 Add coverity in travis
  .travis.yml
Labels: build, code quality

#1313 Added separate user icon from logout icon
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_bg.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ca.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_cs.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_da.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_de.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_el.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en_GB.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_es.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_et.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_fi.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_is.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_it.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ja_JP.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ko.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_mk.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_nl.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_nn.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_no.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pl.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt_BR.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt_PT.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ru.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_sl.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_sv.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_uk.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_zh_CN.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_zh_TW.properties
  airsonic-main/src/main/resources/org/airsonic/player/theme/default_dark.properties
  airsonic-main/src/main/resources/org/airsonic/player/theme/default_light.properties
  airsonic-main/src/main/webapp/WEB-INF/jsp/top.jsp
  airsonic-main/src/main/webapp/icons/default_dark/user.svg
  airsonic-main/src/main/webapp/icons/default_light/user.svg
Labels: enhancement, frontend, usability

#1352 Allow previous Liquibase migration checksums for MariaDB
  airsonic-main/src/main/resources/liquibase/6.3/add-player-mixer.xml
  airsonic-main/src/main/resources/liquibase/6.4/add-album-mb-release-id.xml
  airsonic-main/src/main/resources/liquibase/6.4/add-media-file-mb-release-id.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema25.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema26.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema28.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema29.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema30.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema32.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema35.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema36.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema38.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema43.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema45.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema46.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema47.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema49.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema52.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema53.xml
Labels: backend

#1362 Release 10.4.2
  CHANGELOG.md
  airsonic-main/pom.xml
  airsonic-main/src/main/resources/liquibase/6.3/add-player-mixer.xml
  airsonic-main/src/main/resources/liquibase/6.4/add-album-mb-release-id.xml
  airsonic-main/src/main/resources/liquibase/6.4/add-media-file-mb-release-id.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema25.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema26.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema28.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema29.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema30.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema32.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema35.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema36.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema38.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema43.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema45.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema46.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema47.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema49.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema52.xml
  airsonic-main/src/main/resources/liquibase/legacy/schema53.xml
  airsonic-sonos-api/pom.xml
  install/docker/pom.xml
  integration-test/pom.xml
  pom.xml
  subsonic-rest-api/pom.xml
Labels: release

#1353 Document a bit our review process
  CONTRIBUTING.md
Labels: documentation
