Repository airsonic/airsonic, pull requests merged in 2019-11, with the labels that each got.

#1393 Add jxr plugin for pmd refs
  airsonic-main/pom.xml
Labels: build

#1339 Removed the auto-refresh feature
  airsonic-main/src/main/java/org/airsonic/player/command/PersonalSettingsCommand.java
  airsonic-main/src/main/java/org/airsonic/player/controller/HomeController.java
  airsonic-main/src/main/java/org/airsonic/player/controller/IndexController.java
  airsonic-main/src/main/java/org/airsonic/player/controller/PersonalSettingsController.java
  airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java
  airsonic-main/src/main/java/org/airsonic/player/domain/UserSettings.java
  airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_bg.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ca.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_cs.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_da.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_de.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_el.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en_GB.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_es.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_et.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_fi.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_fr.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_is.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_it.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ja_JP.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ko.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_mk.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_nl.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_nn.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_no.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pl.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt_BR.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt_PT.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ru.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_sl.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_sv.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_uk.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_zh_CN.properties
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_zh_TW.properties
  airsonic-main/src/main/webapp/WEB-INF/jsp/home.jsp
  airsonic-main/src/main/webapp/WEB-INF/jsp/personalSettings.jsp
  airsonic-main/src/test/java/org/airsonic/player/dao/UserDaoTestCase.java
Labels: breaking change, usability

#1413 Added refresh link to all home navigation types
  airsonic-main/src/main/webapp/WEB-INF/jsp/home.jsp
  airsonic-main/src/main/webapp/WEB-INF/jsp/homePager.jsp
Labels: enhancement, frontend

#1397 Update translations for pt_BR
  airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt_BR.properties
Labels: translations
