Repository airsonic/airsonic, pull requests merged in 2020-04, with the labels that each got.

#1131 Added ability to delete the default admin user
  airsonic-main/src/main/java/org/airsonic/player/controller/LoginController.java
  airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
  airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java
  airsonic-main/src/main/java/org/airsonic/player/domain/User.java
  airsonic-main/src/main/java/org/airsonic/player/service/PlaylistService.java
  airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java
Labels: security

#1390 Update Sonos wsdl file
  airsonic-main/src/main/java/org/airsonic/player/service/SonosService.java
  airsonic-sonos-api/src/main/resources/sonos-1.1.wsdl
Labels: dependencies

#1626 Revert escription of a exception in JaudiotaggerParser
  airsonic-main/src/main/java/org/airsonic/player/service/metadata/JaudiotaggerParser.java
Labels: backend, regression

#1453 Upgrade to Spring Boot 2.2
  airsonic-main/pom.xml
  airsonic-main/src/main/java/org/airsonic/player/Application.java
  airsonic-main/src/main/java/org/airsonic/player/TomcatApplication.java
  airsonic-main/src/main/java/org/airsonic/player/monitor/MetricsManager.java
  airsonic-main/src/main/java/org/airsonic/player/security/GlobalSecurityConfig.java
  airsonic-main/src/main/java/org/airsonic/player/spring/LoggingFileOverrideListener.java
  airsonic-main/src/main/java/org/airsonic/player/spring/ServletConfiguration.java
  airsonic-main/src/test/java/org/airsonic/player/api/jukebox/AbstractAirsonicRestApiJukeboxIntTest.java
  airsonic-main/src/test/java/org/airsonic/player/service/InternetRadioServiceTest.java
  airsonic-main/src/test/java/org/airsonic/player/service/PlaylistServiceTestImport.java
  airsonic-sonos-api/pom.xml
  contrib/airsonic.service
  integration-test/pom.xml
  pom.xml
  subsonic-rest-api/pom.xml
Labels: backend, breaking change, dependencies

#1432 Fix playback not starting after adding tracks to an empty play queue
  airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
Labels: frontend, playback

#1660 Try to fix Last.FM scrobbling on AudioScrobbler API v1 (HTTPS not available)
  airsonic-main/src/main/java/org/airsonic/player/service/scrobbler/LastFMScrobbler.java
Labels: regression

#1661 Fix Windows path issue in internal diagnostics page
  airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
Labels: backend
