Repository airsonic/airsonic, pull requests merged in 2020-03, with the labels that each got.

#1565 Disable now defunct chartlyrics lookups
  airsonic-main/src/main/java/org/airsonic/player/ajax/LyricsService.java
Labels: dependencies, workaround

#1545 Correct misleading/broken parameters in PlayQueueService
  airsonic-main/src/main/java/org/airsonic/player/ajax/PlayQueueService.java
Labels: code quality

#1539 Toggle play queue with a button
  airsonic-main/src/main/resources/org/airsonic/player/theme/default_dark.properties
  airsonic-main/src/main/resources/org/airsonic/player/theme/default_light.properties
  airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
  airsonic-main/src/main/webapp/icons/default_dark/chevrons-down.svg
  airsonic-main/src/main/webapp/icons/default_dark/chevrons-up.svg
  airsonic-main/src/main/webapp/icons/default_light/chevrons-down.svg
  airsonic-main/src/main/webapp/icons/default_light/chevrons-up.svg
Labels: frontend
