Repository airsonic/airsonic, pull requests merged in 2020-01, with the labels that each got.

#1454 Turn off Airsonic banner during tests
  airsonic-main/src/test/resources/application.properties
Labels: testsuite

#1460 Avoid exceptions if database is not fully migrated on first startup
  airsonic-main/src/main/java/org/airsonic/player/spring/DatabaseConfiguration.java
Labels: backend

#1459 Avoid exceptions if Lucene index is not ready on first startup
  airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java
Labels: backend

#1466 Fix two possible nullptr deref
  airsonic-main/src/main/java/org/airsonic/player/controller/CoverArtController.java
  airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
Labels: code quality

#1468 Set limit in random track query itself instead of in connection
  airsonic-main/src/main/java/org/airsonic/player/dao/AbstractDao.java
  airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
Labels: performance
