Repository airsonic/airsonic, pull requests merged in 2020-05, with the labels that each got.

#1664 Fix UTF-8 detection on some systems using non-standard locales
  airsonic-main/src/main/java/org/airsonic/player/controller/InternalHelpController.java
  airsonic-main/src/main/webapp/WEB-INF/jsp/internalhelp.jsp
Labels: backend

#1663 fix Jukebox API test under windows
  airsonic-main/src/test/java/org/airsonic/player/api/jukebox/AbstractAirsonicRestApiJukeboxIntTest.java
Labels: testsuite

#1345 Automatically upgrade HSQLDB to 2.5.0
  airsonic-main/pom.xml
  airsonic-main/src/main/java/org/airsonic/player/Application.java
  airsonic-main/src/main/java/org/airsonic/player/dao/LegacyHsqlDaoHelper.java
  airsonic-main/src/main/java/org/airsonic/player/dao/PlayQueueDao.java
  airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
  airsonic-main/src/main/java/org/airsonic/player/spring/DatabaseConfiguration.java
  airsonic-main/src/main/java/org/airsonic/player/util/LegacyHsqlUtil.java
  airsonic-main/src/test/java/org/airsonic/player/TestCaseUtils.java
  airsonic-main/src/test/java/org/airsonic/player/api/jukebox/AbstractAirsonicRestApiJukeboxIntTest.java
  airsonic-main/src/test/java/org/airsonic/player/dao/PodcastDaoTestCase.java
  airsonic-main/src/test/java/org/airsonic/player/dao/UserDaoTestCase.java
Labels: backend, breaking change, database, dependencies

#1686 Add some null-checks on calls to mediaFileService.getMediaFile()
  airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
  airsonic-main/src/main/java/org/airsonic/player/service/RatingService.java
Labels: in: UNKNOWN-backend

#1617 Upgrade JRE from 8 to 11 in Docker image
  install/docker/Dockerfile
Labels: in: docker, type: dependency-upgrade

#1716 Bump Spring Boot from 2.2.6.RELEASE to 2.2.7.RELEASE
  airsonic-main/pom.xml
  pom.xml
Labels: type: dependency-upgrade

#1688 Document how to update the stable release used for version checks
  contrib/release.md
Labels: type: documentation
